# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\mytrader\BackTestGUI\BackTestWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("BackTest")
        Dialog.resize(1031, 719)
        '''self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(790, 30, 191, 81))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")'''
        self.orderflow = QtWidgets.QTableView(Dialog)
        self.orderflow.setGeometry(QtCore.QRect(20, 30, 301, 281))
        self.orderflow.setObjectName("orderflow")
        self.orderlist = QtWidgets.QTableView(Dialog)
        self.orderlist.setGeometry(QtCore.QRect(20, 340, 301, 311))
        self.orderlist.setObjectName("orderlist")
        self.histogram = QtWidgets.QGraphicsView(Dialog)
        self.histogram.setGeometry(QtCore.QRect(370, 130, 611, 521))
        self.histogram.setObjectName("histogram")
        self.strategy = QtWidgets.QListView(Dialog)
        self.strategy.setGeometry(QtCore.QRect(370, 30, 211, 81))
        self.strategy.setObjectName("strategy")

        self.retranslateUi(Dialog)
        '''self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)'''
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))


