# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\mytrader\BackTestGUI\Mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1080, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.orderflow = QtWidgets.QTableView(self.centralwidget)
        self.orderflow.setGeometry(QtCore.QRect(20, 20, 256, 311))
        self.orderflow.setObjectName("orderflow")
        self.uodata_orderflow()

        self.orderlist = QtWidgets.QTableView(self.centralwidget)
        self.orderlist.setGeometry(QtCore.QRect(20, 360, 256, 331))
        self.orderlist.setObjectName("orderlist")
        
        self.histogram = QtWidgets.QGraphicsView(self.centralwidget)
        self.histogram.setGeometry(QtCore.QRect(310, 190, 731, 501))
        self.histogram.setObjectName("histogram")
        
        self.strategy = QtWidgets.QTableView(self.centralwidget)
        self.strategy.setGeometry(QtCore.QRect(310, 20, 401, 141))
        self.strategy.setObjectName("strategy")
        
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

    def uodata_orderflow(self):
        self.model = QtGui.QStandardItemModel(4,3)
        self.model.setHorizontalHeaderLabels(['id','姓名','年龄'])
        self.orderflow.setModel(self.model)
        item11 = QtGui.QStandardItem('10')
        item12 = QtGui.QStandardItem('张三')
        item13 = QtGui.QStandardItem('123')
        self.model.setItem(0,0,item11)
        self.model.setItem(0,1,item12)
        self.model.setItem(0,2,item13)
        self.orderflow.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        # pass

    def uodata_orderlist(self):
        pass

    def uodata_strategy(self):
        pass

    def uodata_histogram(self):
        pass