# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\mytrader\BackTestGUI\Mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1080, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.orderflow = QtWidgets.QTableView(self.centralwidget)
        self.orderflow.setGeometry(QtCore.QRect(20, 20, 256, 311))
        self.orderflow.setObjectName("orderflow")
        '''orderf = [["","","",""],["","","",""],["","","",""]]
        self.uodata_orderflow(orderf)'''

        self.orderlist = QtWidgets.QTableView(self.centralwidget)
        self.orderlist.setGeometry(QtCore.QRect(20, 360, 256, 331))
        self.orderlist.setObjectName("orderlist")
        
        self.histogram = QtWidgets.QGraphicsView(self.centralwidget)
        self.histogram.setGeometry(QtCore.QRect(310, 190, 731, 501))
        self.histogram.setObjectName("histogram")
        
        self.strategy = QtWidgets.QTableView(self.centralwidget)
        self.strategy.setGeometry(QtCore.QRect(310, 20, 401, 141))
        self.strategy.setObjectName("strategy")
        
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

    def uodata_orderflow(self, orderf):
        self.model = QtGui.QStandardItemModel()
        self.model.setHorizontalHeaderLabels(['操作', '方向', '价位', '容量'])
        self.orderflow.setModel(self.model)
        for order in orderf:
            item1 = QtGui.QStandardItem(order[0])
            item2 = QtGui.QStandardItem(order[1])
            item3 = QtGui.QStandardItem(str(order[2]))
            item4 = QtGui.QStandardItem(str(order[3]))
            self.model.appendRow([item1,item2,item3,item4])
        self.orderflow.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        # pass

    def uodata_orderlist(self):
        pass

    def uodata_strategy(self):
        pass

    def uodata_histogram(self):
        pass

class MyWindow(QtWidgets.QMainWindow,Ui_MainWindow):
  def __init__(self):
    super(MyWindow,self).__init__()
    self.setupUi(self)